version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.multistage
    image: bktr_app_one
    container_name: bktrml_app
    restart: always
    ports:
      - '8888:81'
