FROM node:16 AS build-stage

ARG NPM_LOGIN
ARG NPM_PASSWORD

WORKDIR /app 

COPY package*.json ./

RUN npm ci 

COPY ./ ./

RUN npm run build

FROM nginx

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build-stage /app/dist .

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
